  CSS[m
  ZVH1-2-HTML[m
  almantas_leika[m
  feature/CTA[m
  feature/benefits_desktop[m
  feature/form_section_desktop[m
  fix/links[m
  fix/links2[m
  fix/links3[m
  git_CSS_classes[m
* [32mmaster[m
  origin/master[m
  [31mremotes/origin/CSS[m
  [31mremotes/origin/HEAD[m -> remotes/origin/master
  [31mremotes/origin/ZVH1-2-HTML[m
  [31mremotes/origin/almantas_leika[m
  [31mremotes/origin/almantasleika-spec-patch-1[m
  [31mremotes/origin/approve-test[m
  [31mremotes/origin/feature/CTA[m
  [31mremotes/origin/feature/benefits_desktop[m
  [31mremotes/origin/feature/easy_to_implement[m
  [31mremotes/origin/feature/hero_section_desktop[m
  [31mremotes/origin/feature/navigation_bar_desktop[m
  [31mremotes/origin/feature/partners_section_desktop[m
  [31mremotes/origin/feature/partners_section_desktop1[m
  [31mremotes/origin/feature/pricing_plans_page[m
  [31mremotes/origin/feature/simple_UI[m
  [31mremotes/origin/fix/HTML_style_sheet_class_update[m
  [31mremotes/origin/fix/HTML_style_sheet_class_update_2[m
  [31mremotes/origin/fix/links[m
  [31mremotes/origin/fix/links2[m
  [31mremotes/origin/fix/links3[m
  [31mremotes/origin/git_CSS_classes[m
  [31mremotes/origin/juomu02-patch-1[m
  [31mremotes/origin/juomu02-patch-2[m
  [31mremotes/origin/master[m
